export const departments = [
  // --- Administration, Management & Social Sciences ---
  "Accounting",
  "Actuarial Science",
  "Banking and Finance",
  "Business Administration",
  "Business Management",
  "Cooperative and Rural Development",
  "Criminology and Security Studies",
  "Demography and Social Statistics",
  "Economics",
  "Entrepreneurship",
  "Finance",
  "Hospitality and Tourism Management",
  "Human Resource Management",
  "Industrial Relations and Personnel Management (IRPM)",
  "Insurance",
  "International Relations",
  "Marketing",
  "Peace and Conflict Resolution",
  "Political Science",
  "Project Management",
  "Psychology",
  "Public Administration",
  "Social Works",
  "Sociology",
  "Sociology and Anthropology",
  "Taxation",
  "Tourism Studies",

  // --- Arts & Humanities ---
  "Arabic Studies",
  "Christian Religious Studies (CRS)",
  "Communication Arts",
  "Creative Arts",
  "Curriculum Studies",
  "English Language",
  "English and Literary Studies",
  "Fine Arts",
  "French",
  "Hausa",
  "History",
  "History and International Studies",
  "Igbo",
  "Islamic Studies",
  "Linguistics",
  "Linguistics Igbo/Yoruba",
  "Linguistics and Communication Studies",
  "Literature In English",
  "Mass Communication",
  "Media and Communication Studies",
  "Music",
  "Performing Arts",
  "Philosophy",
  "Russian",
  "Theatre Arts",
  "Theology",
  "Yoruba",
  "Chinese",

  // --- Sciences & Technology ---
  "Architecture",
  "Biochemistry",
  "Bio-Informatics",
  "Biology",
  "Botany",
  "Chemistry",
  "Computer Science",
  "Cyber Security Science",
  "Environmental Management",
  "Geography",
  "Geography and Planning",
  "Geology",
  "Geophysics",
  "Industrial Chemistry",
  "Industrial Mathematics",
  "Information Communication Engineering",
  "Information Resource Management",
  "Information Systems",
  "Information Technology",
  "Mathematics",
  "Meteorology and Climate Change",
  "Microbiology",
  "Physics",
  "Physics with Electronics",
  "Plant Science",
  "Statistics",
  "Zoology",
  "Science Laboratory Technology",

  // --- Engineering & Environmental Sciences ---
  "Aerospace Engineering",
  "Agricultural Engineering",
  "Agricultural and Biosystems Engineering",
  "Automobile Engineering",
  "Biomedical Engineering",
  "Building Technology",
  "Chemical Engineering",
  "Civil Engineering",
  "Computer Engineering",
  "Electrical Engineering",
  "Electronic Engineering",
  "Engineering Physics",
  "Estate Management",
  "Food Science and Engineering",
  "Industrial and Production Engineering",
  "Marine Engineering",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Materials and Metallurgical Engineering",
  "Mining Engineering",
  "Petroleum Engineering",
  "Polymer and Textile Engineering",
  "Production and Industrial Engineering",
  "Quantity Surveying",
  "Structural Engineering",
  "Surveying and Geoinformatics",
  "Systems Engineering",
  "Telecommunication Engineering",
  "Urban and Regional Planning",
  "Water Resources and Environmental Engineering",
  "Water Resources Management and Agrometerorology",
  "Software Engineering",

  // --- Medical, Pharmaceutical & Health Sciences ---
  "Anatomy",
  "Dentistry",
  "Human Nutrition and Dietetics",
  "Medical Laboratory Science / Technology",
  "Medical Rehabilitation",
  "Medicine and Surgery",
  "Nursing Science",
  "Optometry",
  "Pharmacy",
  "Pharmacology",
  "Physiology",
  "Physiotherapy",
  "Public Health",
  "Public Health Technology",
  "Radiography",
  "Veterinary Medicine",

  // --- Agriculture ---
  "Agricultural Economics",
  "Agricultural Economics/Extension",
  "Agricultural Extension",
  "Agricultural Science",
  "Agriculture",
  "Agronomy",
  "Animal Production",
  "Animal Science",
  "Crop Production",
  "Crop Science",
  "Family, Nutrition And Consumer Sciences",
  "Fisheries",
  "Food Science and Technology",
  "Forestry",
  "Home Economics",
  "Soil Science",

  // --- Education ---
  "Accounting Education",
  "Adult Education",
  "Agricultural Education",
  "Agricultural Science and Education",
  "Arts Education",
  "Business Education",
  "Communication and Language Arts Education",
  "Computer Education",
  "Counsellor Education",
  "Early Childhood Education",
  "Education and Accountancy",
  "Education and Arabic",
  "Education and Biology",
  "Education and Business Administration",
  "Education and Chemistry",
  "Education and Christian Religious Studies",
  "Education and Computer Science",
  "Education and Economics",
  "Education and English Language",
  "Education and English Language and Literature",
  "Education and Fine Art",
  "Education and French",
  "Education and Geography",
  "Education and Government",
  "Education and History",
  "Education and Home Economics",
  "Education and Igbo",
  "Education and Integrated Science",
  "Education and Islamic Studies",
  "Education and Mass Communication",
  "Education and Mathematics",
  "Education and Physics",
  "Education and Religious Studies",
  "Education and Social Studies",
  "Education and Yoruba Language",
  "Education Administration",
  "Education Management and Planning",
  "Educational Administration and Planning",
  "Educational Foundations",
  "Educational Foundations and Counselling",
  "Educational Management",
  "Educational Technology & Library Studies",
  "Environmental Education",
  "French Language Education",
  "Geography Education",
  "Guidance and Counseling",
  "Health Education",
  "History Education",
  "Home Economics Education",
  "Human Kinetics",
  "Human Physical and Health Education",
  "Library and Information Science",
  "Logistics and Supply Chain Management",
  "Mathematics Education",
  "Physical and Health Education",
  "Primary Education Studies",
  "Science and Technology Education",
  "Secretarial Administration and Education",
  "Secretarial Education",
  "Social Studies and Civic Education",
  "Special Education and Rehabilitation Sciences",
  "Statistics / Computer Science Education",
  "Teacher Education Science",
  "Vocational and Technical Education",
  "Vocational Industrial Education",
  "Woodwork / Education",

  // --- Law ---
  "Law",
  "Islamic and Common Law",
];
